# Generated by Django 5.1.1 on 2024-09-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('asunto', models.CharField(choices=[('calle', 'Calle en mal estado'), ('alumbrado', 'Alumbrado público'), ('drenaje', 'Daño a drenaje'), ('tuberia', 'Daño a tubería de agua'), ('otros', 'Otros')], max_length=50)),
                ('mensaje', models.TextField()),
                ('enlace_ubicacion', models.URLField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
            ],
        ),
    ]
