# Generated by Django 5.1.1 on 2024-10-03 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0008_gasolinera_imagengasolinera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='tramites/imagenes/')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='noticias.tramite')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tramites/archivos/')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='noticias.tramite')),
            ],
        ),
    ]
