# Generated by Django 5.1.1 on 2024-10-04 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0010_servicio_imagenservicio_archivoservicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='descripcion',
            new_name='contenido',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='noticias/imagenes/')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='noticias.noticia')),
            ],
        ),
    ]
