# Generated by Django 5.1.1 on 2024-10-04 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_rename_contenido_noticia_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='eventos/imagenes/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='noticias.evento')),
            ],
        ),
    ]
