# Generated by Django 5.1.1 on 2024-10-04 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_corporacionactual_imagencorporacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporacionactual',
            options={'verbose_name': 'Corporación Actual', 'verbose_name_plural': 'Corporación Actual'},
        ),
    ]
