# Generated by Django 5.1.1 on 2024-10-04 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0015_alter_corporacionactual_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaCantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(max_length=2000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historia de Cantel',
                'verbose_name_plural': 'Historia de Cantel',
            },
        ),
        migrations.CreateModel(
            name='ImagenHistoriaCantel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='historia_cantel/imagenes/')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='noticias.historiacantel')),
            ],
        ),
    ]
