# Generated by Django 5.1.1 on 2024-10-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0017_inicio_imagenedificiomunicipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='imagen_edificio_municipal',
            field=models.ImageField(blank=True, null=True, upload_to='edificio_municipal/'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='imagen_escudo_municipal',
            field=models.ImageField(blank=True, null=True, upload_to='escudo_municipal/'),
        ),
    ]
