# Generated by Django 5.1.1 on 2024-10-04 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0018_alter_inicio_imagen_edificio_municipal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inicio',
            name='imagen_edificio_municipal',
        ),
        migrations.RemoveField(
            model_name='inicio',
            name='imagen_escudo_municipal',
        ),
        migrations.CreateModel(
            name='ImagenEscudoMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='escudo_municipal/')),
                ('inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_escudo', to='noticias.inicio')),
            ],
        ),
    ]
