"""
Django settings for cantel_backend project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n$r%i@4&+jlogqn8qggcy!zv$)o$p^9)iocm11stv$8ft!lft8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['muni-backend.onrender.com', '127.0.0.1', 'localhost']

# Usar cookies seguras solo a través de HTTPS (importante si tienes habilitado HTTPS)
SESSION_COOKIE_SECURE = True

# Prevenir que las cookies de sesión sean accesibles desde JavaScript (protección contra ataques XSS)
SESSION_COOKIE_HTTPONLY = True

# Definir el tiempo de expiración de la sesión (en segundos)
SESSION_COOKIE_AGE = 600

# Cerrar la sesión automáticamente cuando se cierre el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Configurar una política de referer segura para evitar que se comparta información de origen sensible
SECURE_REFERRER_POLICY = 'same-origin'

X_FRAME_OPTIONS = 'DENY'  # Evitar que la página sea cargada en un iframe
SECURE_BROWSER_XSS_FILTER = True  # Filtro anti-XSS del navegador
SECURE_CONTENT_TYPE_NOSNIFF = True  # Evita que el navegador adivine el tipo de contenido

# Application definition

INSTALLED_APPS = [
    'axes',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'noticias',
    'rest_framework',
    'corsheaders',
]

AUTHENTICATION_BACKENDS = (
    'axes.backends.AxesStandaloneBackend',  # Cambiar al nuevo backend
    'django.contrib.auth.backends.ModelBackend',
)

JAZZMIN_SETTINGS = {
    "site_title": "Administración Cantel",
    "site_header": "Municipalidad de Cantel",
    "site_brand": "Cantel",
    "welcome_sign": "Municipalidad de Cantel Administracion 2024-2028",
    "copyright": "Municipalidad de Cantel",
    "search_model": "auth.User",  # Modelo de búsqueda en la barra superior

    # Fondo de la barra lateral
    "navigation_background_color": "bg-primary",
    "topmenu_links": [
        # Enlaces adicionales en el menú superior
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
    ],
    
    # Colores personalizados para el tema
    "theme": "cosmo",  # Otros temas: cerulean, darkly, flatly, lumen, etc.
    
    # Íconos en los módulos
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    # Logo personalizado
    #"site_logo": "ruta/a/tu/logo.png",  # Cambia esta ruta al logo que desees
}

MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cantel_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cantel_backend.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'municipalidad_cantel',
        'USER': 'munidb',
        'PASSWORD': 'Muni2024admin',
        'HOST': 'db-muni.cbwe0gmysorw.us-east-2.rds.amazonaws.com',
        'PORT': '3306',
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
LANGUAGE_CODE = 'es'
TIME_ZONE = 'America/Guatemala'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # Definir STATIC_ROOT para producción
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Definir carpeta para archivos estáticos adicionales

# Media files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de CORS
CORS_ALLOW_ALL_ORIGINS = True

# Configuración de seguridad adicional
CSRF_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True


#XD