# Generated by Django 5.1.1 on 2024-10-20 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0020_imagenpalaciomunicipal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corporacionactual',
            options={},
        ),
        migrations.AlterModelOptions(
            name='historiacantel',
            options={},
        ),
    ]
