# Generated by Django 5.1.1 on 2024-10-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_rename_descripcion_noticia_contenido_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='contenido',
            new_name='descripcion',
        ),
    ]
