# Generated by Django 5.1.1 on 2024-10-04 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0019_remove_inicio_imagen_edificio_municipal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenPalacioMunicipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='palacio_municipal/')),
                ('inicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes_palacio', to='noticias.inicio')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenEdificioMunicipal',
        ),
    ]
